package in.co.vertex.feedback.model;

// Generated Mar 29, 2010 6:46:32 PM by Hibernate Tools 3.2.4.GA

/**
 * Answer generated by hbm2java
 */
public class Answer implements java.io.Serializable {

	private int answerId;
	private String comment;
	private Question questionId;
	private Option optionId;
	private User userId;
	private Form formId;
	private Batch batchId;

	public Answer() {
	}

	public Answer(String comment, Question questionId, Option optionId,
			User userId, Form formId, Batch batchId) {
		this.comment = comment;
		this.questionId = questionId;
		this.optionId = optionId;
		this.userId = userId;
		this.formId = formId;
		this.batchId = batchId;
	}

	public int getAnswerId() {
		return this.answerId;
	}

	public void setAnswerId(int answerId) {
		this.answerId = answerId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Question getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Question questionId) {
		this.questionId = questionId;
	}

	public Option getOptionId() {
		return this.optionId;
	}

	public void setOptionId(Option optionId) {
		this.optionId = optionId;
	}

	public User getUserId() {
		return this.userId;
	}

	public void setUserId(User userId) {
		this.userId = userId;
	}

	public Form getFormId() {
		return this.formId;
	}

	public void setFormId(Form formId) {
		this.formId = formId;
	}

	public Batch getBatchId() {
		return this.batchId;
	}

	public void setBatchId(Batch batchId) {
		this.batchId = batchId;
	}

}
