package in.co.vertex.feedback.model;

// Generated Mar 29, 2010 6:46:32 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Batch generated by hbm2java
 */
public class Batch implements java.io.Serializable {

	private int batchId;
	private String batchName;
	private Date startDate;
	private Date endDate;
	private Set<User> users = new HashSet<User>(0);
	private Form formId;

	public Batch() {
	}

	public Batch(String batchName, Date startDate, Date endDate, Form formId) {
		this.batchName = batchName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.formId = formId;
	}

	public Batch(String batchName, Date startDate, Date endDate,
			Set<User> users, Form formId) {
		this.batchName = batchName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.users = users;
		this.formId = formId;
	}

	public int getBatchId() {
		return this.batchId;
	}

	public void setBatchId(int batchId) {
		this.batchId = batchId;
	}

	public String getBatchName() {
		return this.batchName;
	}

	public void setBatchName(String batchName) {
		this.batchName = batchName;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public Form getFormId() {
		return this.formId;
	}

	public void setFormId(Form formId) {
		this.formId = formId;
	}

}
