package in.co.vertex.feedback.model;

// Generated Mar 29, 2010 6:46:32 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Form generated by hbm2java
 */
public class Form implements java.io.Serializable {

	private int formId;
	private String label;
	private Set<Question> questions = new HashSet<Question>(0);

	public Form() {
	}

	public Form(String label) {
		this.label = label;
	}

	public Form(String label, Set<Question> questions) {
		this.label = label;
		this.questions = questions;
	}

	public int getFormId() {
		return this.formId;
	}

	public void setFormId(int formId) {
		this.formId = formId;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
