package in.co.vertex.feedback.model;

// Generated Mar 29, 2010 6:46:32 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
public class Question implements java.io.Serializable {

	private int questionId;
	private String label;
	private Set<Option> options = new HashSet<Option>(0);
	private Set<Form> forms = new HashSet<Form>(0);

	public Question() {
	}

	public Question(String label) {
		this.label = label;
	}

	public Question(String label, Set<Option> options, Set<Form> forms) {
		this.label = label;
		this.options = options;
		this.forms = forms;
	}

	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Set<Option> getOptions() {
		return this.options;
	}

	public void setOptions(Set<Option> options) {
		this.options = options;
	}

	public Set<Form> getForms() {
		return this.forms;
	}

	public void setForms(Set<Form> forms) {
		this.forms = forms;
	}

}
