package in.co.vertex.feedback.model;

// Generated Mar 29, 2010 6:46:32 PM by Hibernate Tools 3.2.4.GA

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int Id;
	private String userId;
	private String password;
	private String fullname;

	public User() {
	}

	public User(String userId, String password, String fullname) {
		this.userId = userId;
		this.password = password;
		this.fullname = fullname;
	}

	public int getId() {
		return this.Id;
	}

	public void setId(int Id) {
		this.Id = Id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

}
